export const environment = {
   production: true,
   url: "http://localhost:8080/ApplicationPortfolioManager/services/",
   redirectURL: "https://mycovapps.com/Integra/callback",
   clientId:"0oamideozdEJh3H650h7",
   oktaUrl:"https://dev-453625.oktapreview.com/oauth2/aus17p35asecGT0j50h8",
   appName:"ParentIntgera",
   logoutUrl:"https://mycovapps.com/Integra",
   IAMToken:"/IAMApplication",
   electionURL:"/IAMApplication/services",
    baseUrl:"/forrest/",
   localityBaseUrl:"/IntegraLocality/services/",
   help:"/IntegraHelp/help.js",
   helpCss:"/IntegraHelp/styles.css",
   locations:"/IntegraVotingLocations/votinglocations.js",
   postLogoutRedirectUri:"https://mycovapps.com/Integra/agree",
   notifications:"/SochNotificationFE/sochnotification.js",
   electionschedule:"/SochElectionSchedule/sochelectionschedule.js",
   sochElements:"/SochElements/sochElements.js",
   irms:"/irmsFE/irms.js",
   sochTable:"/sochagtable/sochag.js",
}
